### ISSUE TITLE
Can't get the --graph option working...

### ISSUE THREAD

**Issue by lpgauth** [justinkirby/emetric#1]
Any ideas?

```
plotr (master) [1.8.7]$ /opt/local/bin/python2.6 plotr.py --data=emetric_node_name@localhost_20110823162349.csv --graph
sys_active
Traceback (most recent call last):
  File "plotr.py", line 564, in <module>
    sys.exit(main())
  File "plotr.py", line 554, in main
    headless(options,interesting,data)
  File "plotr.py", line 362, in headless
    plot_gen(pivot_key, i, False)
  File "plotr.py", line 342, in plot_gen
    p.create()
  File "plotr.py", line 251, in create
    self.create_plot(d,cb)
  File "plotr.py", line 283, in create_plot
    pivot_set = pv_conv(data[self.pivot])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/records.py", line 457, in __getitem__
    obj = ndarray.__getitem__(self, indx)
ValueError: field named ejd_hosts_global_sessions not found.
```

**Comment by justinkirby** [comment]
Well the first problem is that plotr.py is a horrible mess and is really hard to get it to work well. By 'work well' I mean get useful graphs from it. If you can use something else to generate graphs I highly recommend you try that.

Secondly, if there is no config specified by --config then plotr assumes you ran this in ejabberd (my personal 90% use case) and there is that ejd_hosts_global_sessions field in the csv. So if you did not run emetric in ejabberd you won't have this field and will need to provide a config.

Of course this leads to the 'what is the config?' ... ummmmm.... good question.

I would look at what value you would like to pivot on,e.g. the second Y axis to have comparison line. Then in plotr.py:357 change the string to the field you want along the second Y axis. It is NOT elegant, but plotr.py is simply too hackish to be elegant. Or you could look at the lines above and figure out the format of the yml file.  OR use the UI. Also not recommended.

If you have a better way of making graphs from the csv data, I am all ears and ready to kill plotr.py and replace it.

**Comment by justinkirby** [comment]
I am half tempted to just rm -fr plotr so no one is tempted to try it.
